name: pexels
description: Pexels.com clone

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: ^0.6.2
  flashy_tab_bar2: ^0.0.6
  simple_animations: ^4.2.0
  ionicons: ^0.2.2
  google_fonts: ^4.0.3
  buttons_tabbar: ^1.3.6
  supercharged: ^2.1.1
  share: ^2.0.4
  gallery_saver: ^2.3.2
  photo_view: ^0.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
    - family: Sofia Sans Semi Condensed
      fonts:
        - asset: assets/fonts/SofiaSansSemiCondensed-Black.ttf
        - asset: assets/fonts/SofiaSansSemiCondensed-Bold.ttf
        - asset: assets/fonts/SofiaSansSemiCondensed-ExtraBold.ttf
        - asset: assets/fonts/SofiaSansSemiCondensed-Light.ttf
        - asset: assets/fonts/SofiaSansSemiCondensed-Medium.ttf
        - asset: assets/fonts/SofiaSansSemiCondensed-Regular.ttf
        - asset: assets/fonts/SofiaSansSemiCondensed-SemiBold.ttf

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
