// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnkAmHZsaEAD6U3VzUfQBmNazCq3i297I',
    appId: '1:591858302006:web:82096009882e6a06ad2c97',
    messagingSenderId: '591858302006',
    projectId: 'pexels-7d2c6',
    authDomain: 'pexels-7d2c6.firebaseapp.com',
    storageBucket: 'pexels-7d2c6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMzYjI6PSQrni5xUot7y3kt4_u_CCWoP0',
    appId: '1:591858302006:android:b69e873f1f286bddad2c97',
    messagingSenderId: '591858302006',
    projectId: 'pexels-7d2c6',
    storageBucket: 'pexels-7d2c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL0gPZSp9T-pom-GrXDl_tPQJmH0Yq18I',
    appId: '1:591858302006:ios:171c17db4d03dadcad2c97',
    messagingSenderId: '591858302006',
    projectId: 'pexels-7d2c6',
    storageBucket: 'pexels-7d2c6.appspot.com',
    iosClientId: '591858302006-f96mi5tkadfmvq49uj5d9aehf6tcb7m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pexels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL0gPZSp9T-pom-GrXDl_tPQJmH0Yq18I',
    appId: '1:591858302006:ios:171c17db4d03dadcad2c97',
    messagingSenderId: '591858302006',
    projectId: 'pexels-7d2c6',
    storageBucket: 'pexels-7d2c6.appspot.com',
    iosClientId: '591858302006-f96mi5tkadfmvq49uj5d9aehf6tcb7m7.apps.googleusercontent.com',
    iosBundleId: 'com.example.pexels',
  );
}
